---
!ruby/object:PluginManager::Config
name: Autoscaler
authors:
  - Aelysya
version: 1.0.0
deps: []
retry_psdk_compatibility_after_plugin_load: false
added_files:
  - Data/configs/autoscaler_config.json